import 'package:flutter/material.dart';

class LearnFlutterPage extends StatelessWidget {
  const LearnFlutterPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Girl with Headphones By Dall-e 2'),
        automaticallyImplyLeading: false,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
      ),
      body: Column(children: [
        Center(child: Image.asset('images/headphones_girl.jpeg')),
        const Divider(
          color: Colors.black,
        ),
        Container(
          margin:  const EdgeInsets.all(5),
          padding: const EdgeInsets.all(10),
          width: double.infinity,
          color: Colors.cyan,
          child: const Center(
              child: Text(
            'This is a phone generated by Dall-e 2',
            style: TextStyle(color: Colors.white),
          )),
        ),
        ElevatedButton(onPressed: () {}, child: const Text('Elevated button')),
        OutlinedButton(onPressed: () {}, child: const Text('Outlined button')),
        TextButton(onPressed: () {}, child: const Text('Text button')),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: const [
            Icon(Icons.co2, color: Colors.red,),
            Text('This is a row widget'),
            Icon(Icons.back_hand,  color: Colors.blue,)
          ],
        )
        
      ]),
    );
  }
}
